[package]
name = "os"
version = "0.1.0"
edition = "2024"

[dependencies]
volatile = "0.4.6"
bitflags = "2.4.1"
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }

[profile.release]
debug = true